### ISSUE TITLE
Install dbus when installing Debian/stretch and later

### ISSUE THREAD

**Issue by jkirk** [grml/grml-debootstrap#102]
Dbus should be installed when installing a Debian/stretch (with systemd) system.

**Comment by mika** [comment]
JFTR, I agree that we should take care of this rather sooner than later. E.g. `systemd-logind` is non-functional if dbus is missing, then `HandlePowerKey=poweroff` option in `/etc/systemd/logind.conf`doesn't have any effect and VM shutdowns are not working.

We should also drop acpi*, see #76, but we need a proper strategy to handle this, because just adding `dbus` to `/etc/debootstrap/packages` _might_ be either surprising for users or break older releases.

**Comment by jkirk** [comment]
I am not sure which releases are currently officially supported (and what "works" really means in the [releasetable.txt](https://github.com/grml/grml-debootstrap/blob/master/releasetable.txt)), but as Debian/bullseye is around the corner which makes it stretch+2, we should think about "just adding" it.

Also I'd like to install `qemu-guest-agent` by default (at least until we refactor `grml-debootstrap` the way we planned it). It does exists (at least) since Debian/jessie, so there should not be too much harm, or?

My current workaround for now is to add both packages in `/etc/debootstrap/packages` before the invocation of `grml-debootstrap`:
```
  root@template-debian-bullseye ~ # apt update ; apt install grml-debootstrap  # install latest version
  [...]
  root@template-debian-bullseye ~ # echo "dbus\nqemu-guest-agent" >> /etc/debootstrap/packages

  root@template-debian-bullseye ~ # grml-debootstrap -r $DEBIAN_RELEASE -t /dev/sda1 --grub /dev/sda --hostname $(hostname) --arch amd64 --password [snip] --mirror http://mirror.hetzner.de/debian/packages
```

**Comment by mika** [comment]
I think installing `dbus` by default might be worth consideration, any objections by anyone? /cc @zeha @evgeni @formorer

I don't think qemu-guest-agent should be shipped by default though, since that's a possible security concern (which users need to be aware of) and very specific to the surrounding environment anyway? Until we have a redesign of grml-debootstrap available, the best option is to set up a custom packages file, IMO.

**Comment by evgeni** [comment]
I'm happy with dbus in the default install. After all, people want usable, not minimal systems *most* of the time.

**Comment by zeha** [comment]
Installing dbus makes sense to me.

**Comment by mika** [comment]
Thanks everyone, just pushed the according change :)
