### ISSUE TITLE
port to Multistrap or Similar for better Build Security

### ISSUE THREAD

**Issue by adrelanos** [grml/grml-debootstrap#120]
Current situation and problem:

`build Debian base image using grml-debootstrap which uses debootstrap with mirror "packages.debian.org" but not "security.debian.org" because debootstrap can build only from one APT source` -> `might fetch vulnerable APT version like with DSA 4371` -> `vulnerable APT is used to apt-get update and dist-upgrade Debian base image using "packages.debian.org" and "security.debian.org"` -> `at this point the build might be compromised`

----

Proposed solution:

It would be better to use multistrap because multistrap can create Debian base images using multiple APT sources, "packages.debian.org" and "security.debian.org".

`build Debian base image using grml-debootstrap which uses multistrap with mirror "packages.debian.org"  and "security.debian.org"` -> `fetch security fixed packages only`

This doesn't only fetch security fixed APT but also never installs any already security fixed packages other than APT (think APT dependencies or anything other that is involved in processing code during installation such as libcurl perhaps).

----

Why? To be prepared for the next apt vulnerability.

* https://www.debian.org/security/2019/dsa-4371
* https://www.debian.org/security/2016/dsa-3733

**Comment by adrelanos** [comment]
Quote https://wiki.debian.org/RISC-V (different context perhaps!) but it mentions `mmdebstrap` as alternative to `multistrap`.

> At the time of writing, mmdebstrap is still rather new, but it provides a largely debootstrap-compatible user interface and can be used as a drop-in replacement for debootstrap in many cases. multistrap already exists for many years, but it behaves quite a bit different from debootstrap and a chroot created with multistrap requires several manual adjustments that aren't necessary when using mmdebstrap. Unless there are specific reasons for using multistrap, the use of mmdebstrap is therefore recommended.

**Comment by mika** [comment]
I'm not really buying the security argument, Debian provides point-releases (this time [9.7](https://packages.qa.debian.org/b/base-files/news/20190122T153207Z.html), very close to the apt 1.4.9 security release and meant exactly for that) and when bootstrapping stretch you get the fixed apt package already as intended, nor?

_But_ supporting `mmdebstrap` for _speed_ reasons (since it's supposed to be 2-3 times faster than debootstrap and its variants) would be worth the effort, IMO. Sadly mmdebstrap is available only starting with Debian/buster yet, so it will be available only to certain users. BTW, we already have support for _deboostrap_ vs _cdebootstrap_ via `$DEBOOTSTRAP` in our config, so if mmdebstrap is interface-compatible with debootstrap, then it should be fairly trivial to support it.

**Comment by mika** [comment]
`DEBOOTSTRAP=mmdebstrap grml-debootstrap ...` works already OOTB, taking 1m45sec inside a VM, while a run with main `debootstrap` takes ~3min30sec.
