### ISSUE TITLE
avoid tune2fs prompt, wait

### ISSUE THREAD

**Issue by adrelanos** [grml/grml-debootstrap#222]
```
tune2fs /dev/mapper/loop0p3 -U 26ada0c0-1165-4098-884d-aafd2220c2c6
tune2fs 1.47.0 (5-Feb-2023)
Setting the UUID on this filesystem could take some time.
Proceed anyway (or wait 5 seconds to proceed) ? (y,N) 
```

The waiting can be avoided. Pull request coming.

**Comment by mika** [comment]
Thanks! For upcoming PRs it would be nice if the commit message in the PR itself would also mention the example like here in the issue (to have a better idea what the actual issue is about), and also refer to it (`Closes: https://github.com/grml/grml-debootstrap/issues/222` or if it's not fully closing it, then something like `Related to https://github.com/grml/grml-debootstrap/issues/222`).

Closing hereby, now that https://github.com/grml/grml-debootstrap/pull/223 is merged
