### ISSUE TITLE
Git HEAD: Potential issues with "apt-get --force-yes ..."

### ISSUE THREAD

**Issue by hartwork** [grml/grml-debootstrap#62]
Hi!

I found that the chroot  script of grml-deboostrap may call `apt-get --force-yes ...`
as of https://github.com/grml/grml-debootstrap/blob/master/chroot-script#L31
if `/usr/bin/aptitude` is missing inside the chroot.

~~Since debootstrap itself seems to install aptitude (I checked for wheezy, only) this _may_ not be much of a practical problem right now.~~
Nevertheless, I am worried that `--force-yes` may lead to installation of packages that fail GPG verification checks, in some weird scenarios already or in in new scenarios in the future.

The man page of `apt-get` says
```
--force-yes
           Force yes; this is a dangerous option that will cause apt to continue without
           prompting if it is doing something potentially harmful. It should not be used
           except in very special situations.
           Using force-yes can potentially destroy your system!
```
I would therefore suggest removing the `--force-yes` parameter.

What do you think?

**Comment by adrelanos** [comment]
Confirmed. Just now tested this.

* `jessie` is affected by this. It uses `apt-get --force-yes -y` (while `-y` stands for `--yes`). This combination is dangerous and would also install unsigned packages.
* `wheezy` is unaffected by this, because `debootstrap` indeed installs `aptitude`.

Could be considered a CVE?

**Comment by hartwork** [comment]
```
for release in wheezy jessie sid; do
    sudo debootstrap ${release} ${release}_root
done
ls -al */usr/bin/aptitude
```
Output is:

**Comment by adrelanos** [comment]
As a workaround, before running grml-debootstrap, running this.
```
export DPKG_OPTIONS="-o APT::Get::force-yes=0"
```
Might help.

(Because running [for example](https://www.whonix.org/wiki/Dev/apt-get#Using_--yes_and_--force-yes_and_-o_APT::Get::force-yes.3D0) `sudo apt-get install --yes --force-yes python-gflags -o APT::Get::force-yes=0` wouldn't install any unsigned packages and just abort. Just did test that.)

What do you think?

**Comment by xtaran** [comment]
JFYI: Jessie no more needs aptitude in the installer because tasksel no more depends on aptitude as it did in the past. So I assume, debootstrap followed that path, either explicitly or implicitly (via aptitude's package priority, which has been lowered, too).

**Comment by xtaran** [comment]
[A similar issue has been reported in xen-tools](https://bugs.debian.org/776487). But in comparison to xen-tools, grml-debootstrap probably doesn't need to be able to install no more supported releases from archive.debian.org or such (debootstrap supports that), so the fix for grml-debootstrap may be easier.

See the bug report for parts of the --force-yes code path inside apt 1.0.9.6 (as of Sid/Jessie currently).

**Comment by mika** [comment]
grml-debootstrap definitely tries to support no-more supported releases from archive.debian.org, so I'm unsure what to do about that. I'm absolutely unhappy that `--force-yes` might result in installing unsigned packages, but just dropping the `--force-yes` option probably just breaks installation of older releases? I'd very much appreciate any help and testing on this (especially testing older releases).

**Comment by hartwork** [comment]
Why is this ticket labelled upstream? Which upstream? I don't get it :)

**Comment by mika** [comment]
upstream of `apt-get`, there doesn't seem to be a solution how to force installation of packages without accepting unsigned packages then.

**Comment by adrelanos** [comment]
> there doesn't seem to be a solution how to force installation of packages without accepting unsigned packages then.

I came to the same conclusion. There is only,

* `-o Acquire::Check-Valid-Until=false` and
* `--allow-unauthenticated`.

-----

My suggestion:

* Disable use of `--force-yes` by default.
* Therefore not using `--force-yes` for secure support of current versions.
* Option to use insecure `--force-yes` for legacy versions.
